version: '2'
services:
  redis:
    image: redis
  db:
    image: postgres
  sidekiq:
    build: .
    volumes:
      - .:/sms_campaign
    command: bundle exec sidekiq
    env_file:
      - .env
    depends_on:
      - db
      - redis
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/sms_campaign
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
