# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 096bc3e9b7fb47c7a8bcd37b7e25fa159eaadd584af29eb243a7415f5f74dcf1a2f6bbadcb6fabe6ea31a9d6ac0f1cb472fa88cf653a57de092e47395d64cc17
  postmark_api_token: 1cad7987-4a84-4da7-9352-fa2ef45172d6

test:
  secret_key_base: fd218eb362cd794495071b0cfed2f2a4798c5a113e943cbd6174e79b9794fb1dc832250e36339839f4546b91ff8f0df5bf06c8d84e8c5f3de676a4ef6cd610c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  postmark_api_token: <%= ENV["POSTMARK_API_TOKEN"] %>
